### ISSUE TITLE
support the omitempty field tag convention

### ISSUE THREAD

**Issue by glycerine** [tinylib/msgp#103]
Thanks for this terrific msgp package.  

This is a small request for a feature/improvement.

The convention in Go's encoding/json package is that a field tagged with "omitempty" is ignored if the field contains the zerovalue for the type. (reference http://golang.org/pkg/encoding/json/#Marshal).

This does make the serialized form more readable (e.g. when translating to json) when there are many optional fields. 

Kindly consider supporting the omitempty tag. For example:

```
type Demo struct {
    Count int `msg:",omitempty"`
    Name string `msg:",omitempty"`
}
```

**Comment by philhofer** [comment]
I'd like to have this feature. However, it presents some implementation complexity.

Due to how messagepack is laid out, you need to know *precisely* the size of the composite (map/array) you're about to write.

In pseudo-code, encoding is done like this:
```
begin_map(len(fields));
for field in fields:
    write_field(field);
```

If you have optional fields, that turns into:
```
num_fields = 0

for field in fields:
    if !is_empty(field)
        num_fields++

begin_map(num_fields)
for field in fields:
    if !is_empty(field)
        write_field(field);
```

For each of the five methods that we generate today, we would have to make substantial changes. Additionally, many optimizations (constant propagation and pre-serialization in particular) depend on knowing statically the number of elements to be encoded. For some users, the performance penalty may be acceptable, but we would have to make sure people understood the tradeoffs that they were making.

**Comment by glycerine** [comment]
Ah, I see.  Well I certainly love the performance, and wouldn't like to give that up.

Since my desire is primary to eliminate the visual clutter for human reading/debugging, perhaps  CopyToJSON could respect the omitempty tag while leaving the generated methods as is?

**Comment by philhofer** [comment]
Certainly. That's much simpler.

**Comment by b1v1r** [comment]
Because the "omitempty" is not supported, there is some compatibility issues in a non-golang client that expects such entries to have nil values. Without this, to switch to msgp I need to rewrite all the non-golang clients to check for not only nil, but an empty string because golang does not support nil strings.

Perhaps support making "empty values" encode as nil and decode to the equivalent when "omitempty" is used? This would mean, for example, that the WriteMap would not have to change the header length, but if it detects an empty string value it would encode the value to `c0` instead of `a0` and would decode a `c0` in ReadString to the empty string. This seems to give a good balance between performance and compatibility with other languages and message pack libs. 

Thoughts?

**Comment by philhofer** [comment]
I'm not sure `omitempty` would be the right name for that tag (since the object field name would still be encoded), but the feature itself seems perfectly reasonable.

**Comment by b1v1r** [comment]
Agreed, not a great name. It is more of a compatibility with existing "omitempty". Maybe "detectnil" or something.

**Comment by philhofer** [comment]
I've taken a shot at this change locally and I think it is simpler and easier to typedef your way into the behavior your want. It's not clear *which* zero-value objects need to be nullable, and whether or not that behavior would be meaningful. (For instance, if the tag meant 'this object is null if it compares equal to the objects zero value,' then `struct{}` would always be encoded as `null` rather than `{}`. There are other such edge-cases, particularly when you have non-comparable structs.)

Here's what I'd suggest for the string case. (You can extrapolate it to the other cases easily.)

```go
type NullableString string

func (n NullableString) MarshalMsg(b []byte) ([]byte, error) {
    if n == "" {
        return msgp.AppendNil(b), nil
    }
    return msgp.AppendString(b, string(n))
}

func (n *NullableString) UnmarshalMsg(b []byte) ([]byte, error) {
    if msgp.IsNil(b) {
        *n = ""
    } else {
        s, o, err := msgp.ReadStringBytes(b)

    }
}
```
... and so forth.

**Comment by glycerine** [comment]
Re the concern about performance impact, I didn't see where constant propagation and pre-serialization where impacted by the draft in #164, so perhaps I missed something. To be extra cautious though, if there are no omitempty tags in use, I left the codegen exactly the same.

It's not urgent, but @philhofer when you have a minute please have a look.

**Comment by glycerine** [comment]
If anyone is interested, I finished the `omitempty` support, as well as a number of other features, in my fork: https://github.com/glycerine/zebrapack.  One can use the `zebrapack -msgp` flag to generate msgpack instead of ZebraPack; and those msgpack encoders will honor the `omitempty` tag.
