### ISSUE TITLE
Type aliasing is not supported in AppendIntf

### ISSUE THREAD

**Issue by imtaco** [tinylib/msgp#115]
```
type MyType string

func main() {
        fmt.Println( msgp.AppendIntf(nil, MyType("somestr")) )
}
```
```
[] msgp: type "main.MyType" not supported
```

**Comment by glycerine** [comment]
As you may realize, it is impossible for a library to support arbitrary types without constraints, since you can make up a new type, as in MyType, at any point in time.  How can a library possibly know how to serialize an arbitrary type?  It cannot. And that's a good thing. The point of making a new type is that you want it to be treated special, and not equivalent to other types. If you want it serialized as a string, then convert it to a string.

msgp.AppendIntf is clearly documented about what it supports. You should convert your MyType to a string at the call point, or define msgp.Marshaller methods or msgp.Extension methods on MyType.

msgp/msgp/write_bytes.go:306
~~~
// AppendIntf appends the concrete type of 'i' to the                           
// provided []byte. 'i' must be one of the following:                           
//  - 'nil'                                                                     
//  - A bool, float, string, []byte, int, uint, or complex                      
//  - A map[string]interface{} or map[string]string                             
//  - A []T, where T is another supported type                                  
//  - A *T, where T is another supported type                                   
//  - A type that satisfies the msgp.Marshaler interface                       
//  - A type that satisfies the msgp.Extension interface                        
func AppendIntf(b []byte, i interface{}) ([]byte, error) {
...
~~~

**Comment by philhofer** [comment]
Yep. This is the intended behavior. The support for encoding/decoding `interface{}` is intentionally minimal; the code generator is there to solve this problem for you.
