### ISSUE TITLE
just a little remark about function "ensure" in write_bytes.go

### ISSUE THREAD

**Issue by rin01** [tinylib/msgp#122]
About function "ensure" in write_bytes.go:10.

The idiomatic way to extend a slice in Go is described here:

https://github.com/golang/go/wiki/SliceTricks

    Extend:
    a = append(a, make([]T, j)...)

In http://play.golang.org/p/qnncZSs54x, the function "ensure_new" is a little bit simpler.

The only difference is that the builtin "append" exactly doubles the capacity, and your function "ensure" makes it grow a little bit more.

**Comment by philhofer** [comment]
Most of the weirdness in the code you're reading is due to trying to convince the go compiler to inline functions that it otherwise wouldn't. `ensure` in particular has gone through quite a bit of tweaking to squeeze every last instruction out of it. (Like, you see that `len(b)` and `cap(b)` are assigned to variables early on? That's because they wouldn't otherwise get stuck in registers for the duration of the function).

You can go draft this change, but I'd bet you'd see a 5-10% performance hit on all of the functions that depend on it.

**Comment by rin01** [comment]
Ah, I understand. Thank you for the explanation ;-)
