### ISSUE TITLE
Non-deterministic function inlining

### ISSUE THREAD

**Issue by nuivall** [tinylib/msgp#239]
I'm experiencing different code generated for the same source.
Here is the diff:
``` 
func (z *UserProcess) DecodeMsg(dc *msgp.Reader) (err error) {
(...)
		case "Output":
-			var zb0003 uint32
-			zb0003, err = dc.ReadMapHeader()
+			err = z.Output.DecodeMsg(dc)
 			if err != nil {
 				return
 			}
-			for zb0003 > 0 {
-				zb0003--
-				field, err = dc.ReadMapKeyPtr()
-				if err != nil {
-					return
-				}
-				switch msgp.UnsafeString(field) {
(...)
```
I think more often inlined (longer) version is generated but not always, like 60%-70% cases.

version: master (f65876d3ea05943d6613bca6b8ed391843044bd4)
go version: go1.11.1 linux/amd64

Please have a look, can provide more code samples if needed, thanks!

**Comment by erikdubbelboer** [comment]
Can you provide the code for the `UserProcess` struct and the code for the type of the `Output` field of the `UserProcess` struct.

**Comment by nuivall** [comment]
Sure! Found smaller example where this happens as well. Thank you for quick response!

```
package models

//go:generate msgp

type FormInput struct {
	ID     string // map key
	Fields FieldInput
	Files  []FileInput
}

type FieldInput map[string]interface{}

type FileInput struct {
	Meta          FileMeta
	FormFieldName string
}

type FileMeta struct {
	UUID        string `json:"uuid"`
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
}
```

**Comment by erikdubbelboer** [comment]
It seems like the issue is with the [inline decision code](https://github.com/tinylib/msgp/blob/54a3260d60646faaba5873316fa01ac61d49c1d5/parse/inline.go#L113). It calls the function `Complexity()` which [for structs](https://github.com/tinylib/msgp/blob/54a3260d60646faaba5873316fa01ac61d49c1d5/gen/elem.go#L396) seems to have non deterministic return value. I looks like sometimes it doesn't know about the members of `FileMeta` yet and returns a complexity that is too low for `FileInput`. I'm guessing because somewhere there is a `map` of structs that needs to be processed and the order of a `map` in Go is random. So sometimes it will process `FileInput` before `FileMeta` in which case it doesn't know the members of `FileMeta` yet. I couldn't locate this exact code so this is still just a guess.

@philhofer what is the reason that msgp decides when to inline a function. Why not keep the code a lot easier and smaller and let the Go compiler decide when to inline or not?
