### ISSUE TITLE
msgp may cause high GC pressure

### ISSUE THREAD

**Issue by sxfworks** [tinylib/msgp#273]
msgp has always been the head of small object distribution in our service. Our service itself has relatively high GC pressure. Is there any way to improve the reuse of small objects within msgp?

go tool pprof --allocs_object /debug/pprof/heap

60031247772 13.46% 13.46% 60031247772 13.46%  github.com/tinylib/msgp/msgp.ReadStringBytes (inline)   UnmarshalMsg

**Comment by philhofer** [comment]
If you're reading lots of small strings, there's not a lot to be done.
There's no extra allocation happening inside the library; all of that
is the memory for the strings themselves.

If your wire protocol is sending a lot of the same strings over and
over, you could intern them (encode them as integers).

**Comment by erikdubbelboer** [comment]
Or use `[]byte` instead of `string` so the memory can be reused (if you reuse your struct).

**Comment by bradleypeabody** [comment]
I recently addressed something similar by writing a custom type that uses []byte internally but encodes as msgpack string type.  The UnmarshalMsg implementation, since it operates on a byte slice, can be made to decode without copying.

```
// ByteString is a byte slice that can return an unsafe casted
// string to its contents.  We use it to mark text that
// should be encoded as a msgpack string, but we don't
// want to be forced to copy the data when parsing.
type ByteString []byte

// ...

// UnmarshalMsg implements msgp.Unmarshaler.  v is backed directly
// by the underlying bytes from bts.
func (v *ByteString) UnmarshalMsg(bts []byte) (o []byte, err error) {
	*v, o, err = msgp.ReadStringZC(bts)
	return o, errutil.ErrLoc(err)
}
```

So you have to carefully control the memory usage when doing something like this, but if you're willing to do that work, you can avoid virtually all allocations during parsing.  But it just requires that the original input bytes, the struct you're parsing into, and types you use inside it - you just have to design those very carefully.  So it's definitely possible to do, it's just a matter of is it worth doing the extra work for your application.  I use msgp a lot and I normally don't bother with this stuff.  But in one particular case the sheer volume of data going through a certain code path warranted this optimization for me.

**Comment by klauspost** [comment]
Yeah. Have a similar, but alternative type here: https://github.com/minio/minio/blob/next/internal/grid/types.go#L132

It will however copy the input, but will reuse any underlying slice if already allocated. This breaks the dependency on the provided `bts []byte` - which in my case I want to re-use.

**Comment by klauspost** [comment]
Closing as this is more of a user issue than a library issue.
