### ISSUE TITLE
Allownil in []byte is useless

### ISSUE THREAD

**Issue by lxyshuai** [tinylib/msgp#362]

**Comment by lxyshuai** [comment]
![Uploading msgp.jpeg…]()

**Comment by lxyshuai** [comment]
![msgp](https://github.com/user-attachments/assets/16df888e-f860-4d39-8495-2aac3f7e3312)

```
package main

import (
	"fmt"
)

//go:generate msgp

type A struct {
	Bytes   []byte   `msg:"bytes,omitempty,allownil"`
	Strings []string `msg:"strings,omitempty,allownil"`
	Ints    []int    `msg:"ints,omitempty,allownil"`
}

func main() {
	a := A{
		Bytes:   make([]byte, 0),
		Strings: make([]string, 0),
		Ints:    make([]int, 0),
	}

	aBytes, _ := a.MarshalMsg(nil)
	aTemp := A{}
	aTemp.UnmarshalMsg(aBytes)

	fmt.Println(aTemp)
}
```

Allownil in []byte is useless

**Comment by klauspost** [comment]
A) Using the latest version the output is `{Bytes:[] Strings:[] Ints:[]}`, not what you show.
B) `omitempty` and `allownil` doesn't make sense together, since both operate on the `nil` value. Adding it will do:

```
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Bytes == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
```

Resulting in the same output, since all are included as 0 length arrays, and therefore it will never emit nil values.

`omitempty` will not omit 0-length slices. This is stated in the [docs](https://github.com/tinylib/msgp/wiki/Zero-Values;-Omitempty-and-Allownil#omitempty) is that it checks against the zero value. The zero value of a `[]byte` is nil.

**Comment by klauspost** [comment]
There is a quirk in `ReadBytesBytes`, where if the array size is 0 a new slice is not allocated if scratch is nil. I will send a fix for that.

**Comment by lxyshuai** [comment]
@klauspost Thank you！
![image](https://github.com/user-attachments/assets/90f35bba-93a5-4ff4-96fb-d6dd9fba9462)
when scratch is nil,ReadBytesBytes return nil

**Comment by klauspost** [comment]
Yes.

**Comment by lxyshuai** [comment]
Should we reopen this issue?
